# This is a basic workflow to help you get started with Actions
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>MethraX Official</title>
  <style>
    body {
      margin: 0;
      font-family: 'Arial Black', sans-serif;
      background-color: black;
      color: white;
      text-align: center;
    }
    .container {
      padding: 40px 20px;
    }
    img {
      width: 100%;
      max-width: 400px;
      margin-top: 20px;
    }
    .tagline {
      font-size: 32px;
      color: #ff0000;
      margin: 20px 0;
    }
    .button {
      background-color: #25d366;
      color: black;
      padding: 15px 30px;
      font-size: 18px;
      border: none;
      border-radius: 10px;
      cursor: pointer;
      text-decoration: none;
    }
    .button:hover {
      background-color: #1ebe57;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>MethraX™</h1>
    <p class="tagline">Unleash the Chaos. Wired to Bone.</p>
    <img src="https://i.ibb.co/
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
